strlen:
	gcc -g -O0 -Wall --std=c99 strlen.c -o strlen
datatypes:
	gcc -g -O0 -Wall --std=c99 datatypes.c -o datatypes
macros:
	gcc -g -O0 -Wall --std=c99 macros.c -o macros
atoi:
	gcc -g -O0 -Wall --std=c99 atoi.c -o atoi

clean:
	rm -f macros
	rm -f datatypes
	rm -f strlen
	rm -f atoi
